<a href="https://colab.research.google.com/github/jitendra19/stock-market-prediction/blob/main/stock_market_prediction_using_ML_techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
pip install yfinance

In [26]:
# Import Python Libraries
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

import seaborn as sns

sns.set_style('whitegrid')

plt.style.use("fivethirtyeight")
%matplotlib inline

# For reading stock data from yahoo
# from pandas_datareader.data import DataReader
import yfinance as yf

# For time stamps
from datetime import datetime

In [27]:
stockName = 'AAPL'
periodOfData = "5y"

# df = DataReader('AAPL', data_source='yahoo', start='2012-01-01', end=datetime.now())
ticker = yf.Ticker(stockName)
df = ticker.history(period=periodOfData, auto_adjust=True)

# Show the data
df.tail()

Open        High  ...  Dividends  Stock Splits
Date                                ...                         
2021-11-29  159.369995  161.190002  ...        0.0           0.0
2021-11-30  159.990005  165.520004  ...        0.0           0.0
2021-12-01  167.479996  170.300003  ...        0.0           0.0
2021-12-02  158.740005  164.199997  ...        0.0           0.0
2021-12-03  164.020004  164.960007  ...        0.0           0.0

[5 rows x 7 columns]

In [28]:
close_df = df[['Close']]
close_df[['Close']].tail()

Close
Date                  
2021-11-29  160.240005
2021-11-30  165.300003
2021-12-01  164.770004
2021-12-02  163.759995
2021-12-03  161.839996

In [41]:
# lets create one more column which is having stock values 15 days in advance, by shifting 15 rows up.
# create Machine learning LR model based on the current and 15 days later values and predict the values 15 days in advance.
close_df['Prediction'] = close_df[['Close']].shift(-15)
#print data set

print('first 15 rows --- ',close_df[0:15])
print('last 15 rows --- ',close_df[-15:])

first 15 rows ---                  Close  Prediction
Date                             
2016-12-05  25.675816   27.593676
2016-12-06  25.873486   27.476017
2016-12-07  26.127630   27.468958
2016-12-08  26.384125   27.254816
2016-12-09  26.814758   27.332472
2016-12-12  26.661812   27.301876
2016-12-13  27.106560   27.440718
2016-12-14  27.106560   27.746635
2016-12-15  27.254816   28.000784
2016-12-16  27.290110   28.029020
2016-12-19  27.447779   28.179626
2016-12-20  27.520733   28.061960
2016-12-21  27.546612   28.012550
2016-12-22  27.365416   28.238457
2016-12-23  27.419544   28.236099
last 15 rows ---                   Close  Prediction
Date                              
2021-11-12  149.990005         NaN
2021-11-15  150.000000         NaN
2021-11-16  151.000000         NaN
2021-11-17  153.490005         NaN
2021-11-18  157.869995         NaN
2021-11-19  160.550003         NaN
2021-11-22  161.020004         NaN
2021-11-23  161.410004         NaN
2021-11-24  161.940002         NaN


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [45]:
print('last 15 rows --- ',close_df[-15:])
print('wihtout last 15 rows --- ',close_df[:-15])

last 15 rows ---                   Close  Prediction
Date                              
2021-11-12  149.990005         NaN
2021-11-15  150.000000         NaN
2021-11-16  151.000000         NaN
2021-11-17  153.490005         NaN
2021-11-18  157.869995         NaN
2021-11-19  160.550003         NaN
2021-11-22  161.020004         NaN
2021-11-23  161.410004         NaN
2021-11-24  161.940002         NaN
2021-11-26  156.809998         NaN
2021-11-29  160.240005         NaN
2021-11-30  165.300003         NaN
2021-12-01  164.770004         NaN
2021-12-02  163.759995         NaN
2021-12-03  161.839996         NaN
wihtout last 15 rows ---                   Close  Prediction
Date                              
2016-12-05   25.675816   27.593676
2016-12-06   25.873486   27.476017
2016-12-07   26.127630   27.468958
2016-12-08   26.384125   27.254816
2016-12-09   26.814758   27.332472
...                ...         ...
2021-11-05  151.279999  160.240005
2021-11-08  150.440002  165.300003
2021-11-09 

In [46]:
#Create a new data set 'xclose_df' and convert it into numpy array , which will be having actual values
xclose_df = np.array(close_df.drop(['Prediction'],1))
#Remove the last 15 rows
xclose_df = xclose_df[:-15]
print(xclose_df)

[[ 25.67581558]
 [ 25.87348557]
 [ 26.12763023]
 ...
 [150.80999756]
 [147.91999817]
 [147.86999512]]


In [47]:
# Create a dataset 'yclose_df' which will be having Predicted values and convert into numpy array
yclose_df = np.array(close_df['Prediction'])
# Remove Last 15 rows
yclose_df = yclose_df[:-15]
print(yclose_df)

[ 27.59367561  27.476017    27.4689579  ... 164.77000427 163.75999451
 161.83999634]


In [48]:
from sklearn.model_selection import train_test_split

from sklearn.svm import SVR


# Split the data into train and test with 90 & 10 % respectively
x_train, x_test, y_train, y_test = train_test_split(xclose_df, yclose_df, test_size=0.1)

# using SVM

In [49]:
# SVM Model
svr = SVR(kernel='rbf', C=1e3, gamma=0.1) # kernel{‘linear’, ‘poly’, ‘rbf’, ‘sigmoid’, ‘precomputed’}, default='rbf'
# Train the model 
svr.fit(x_train, y_train)

SVR(C=1000.0, gamma=0.1)

In [34]:
# The best possible score is 1.0
svm_confidence = svr.score(x_test, y_test)
print('svm confidence: ', svm_confidence)

svm confidence:  0.9816402645399981


In [50]:
# get the last 15 rows of the original data set from Close column and convert into numpy array
forecast = np.array(close_df.drop(['Prediction'],1))[-15:]
print(forecast)

[[149.99000549]
 [150.        ]
 [151.        ]
 [153.49000549]
 [157.86999512]
 [160.55000305]
 [161.02000427]
 [161.41000366]
 [161.94000244]
 [156.80999756]
 [160.24000549]
 [165.30000305]
 [164.77000427]
 [163.75999451]
 [161.83999634]]


In [54]:
# support vector model predictions for the next ‘15’ days
svm_prediction = svr.predict(forecast)

for i in range(15):
    print(forecast[i][0], ' ---> ',svm_prediction[i])

# print(svm_prediction)
# print(forecast)

149.99000549316406  --->  155.06788819337766
150.0  --->  155.11169924359234
151.0  --->  156.74337709548945
153.49000549316406  --->  141.87834824818486
157.8699951171875  --->  132.14517949450874
160.5500030517578  --->  105.40026980243105
161.02000427246094  --->  102.06431951745655
161.41000366210938  --->  99.86758061690057
161.94000244140625  --->  97.65807633380942
156.80999755859375  --->  139.96657402537096
160.24000549316406  --->  107.9998017827059
165.3000030517578  --->  94.30615562320774
164.77000427246094  --->  94.35495166599428
163.75999450683594  --->  94.65208271672437
161.83999633789062  --->  98.01199802192697


In [56]:
from prettytable import PrettyTable

myTable = PrettyTable(["closing price", "Prediction"]) 

for i in range(15):
    # print(forecast[i][0], ' ---> ',svm_prediction[i])
    myTable.add_row([forecast[i][0], svm_prediction[i]])

print(myTable)

+--------------------+--------------------+
|   closing price    |     Prediction     |
+--------------------+--------------------+
| 149.99000549316406 | 155.06788819337766 |
|       150.0        | 155.11169924359234 |
|       151.0        | 156.74337709548945 |
| 153.49000549316406 | 141.87834824818486 |
| 157.8699951171875  | 132.14517949450874 |
| 160.5500030517578  | 105.40026980243105 |
| 161.02000427246094 | 102.06431951745655 |
| 161.41000366210938 | 99.86758061690057  |
| 161.94000244140625 | 97.65807633380942  |
| 156.80999755859375 | 139.96657402537096 |
| 160.24000549316406 | 107.9998017827059  |
| 165.3000030517578  | 94.30615562320774  |
| 164.77000427246094 | 94.35495166599428  |
| 163.75999450683594 | 94.65208271672437  |
| 161.83999633789062 | 98.01199802192697  |
+--------------------+--------------------+


# Using Linear Regression

In [58]:
from sklearn.linear_model import LinearRegression

In [59]:
# Linear Regression Model
lr = LinearRegression()
# Train the model
lr.fit(x_train, y_train)

LinearRegression()

In [60]:
# Testing Model: Return the coefficient of determination R² of the prediction.

# The best possible score is 1.0
lr_confidence = lr.score(x_test, y_test)
print(lr_confidence)

0.986985520359951


In [61]:
# get the last 15 rows of the original data set from Adj. Close column and convert into numpy array

forecast = np.array(close_df.drop(['Prediction'],1))[-15:]
print(forecast)

[[149.99000549]
 [150.        ]
 [151.        ]
 [153.49000549]
 [157.86999512]
 [160.55000305]
 [161.02000427]
 [161.41000366]
 [161.94000244]
 [156.80999756]
 [160.24000549]
 [165.30000305]
 [164.77000427]
 [163.75999451]
 [161.83999634]]


In [62]:
# linear regression model predictions for the next 15 days
lr_prediction = lr.predict(forecast)
print(lr_prediction)

[152.68789525 152.69802548 153.71160513 156.23542403 160.67489238
 163.39129389 163.86767756 164.26297301 164.80016899 159.60050043
 163.07708667 168.20579723 167.66860125 166.64487591 164.69880483]


In [63]:
from prettytable import PrettyTable

myTable = PrettyTable(["closing price", "Prediction"]) 

for i in range(15):
    myTable.add_row([forecast[i][0], lr_prediction[i]])

print(myTable)

+--------------------+--------------------+
|   closing price    |     Prediction     |
+--------------------+--------------------+
| 149.99000549316406 | 152.6878952464989  |
|       150.0        | 152.6980254752517  |
|       151.0        | 153.71160512646577 |
| 153.49000549316406 | 156.23542402574816 |
| 157.8699951171875  | 160.6748923811872  |
| 160.5500030517578  | 163.39129388875995 |
| 161.02000427246094 | 163.86767756211043 |
| 161.41000366210938 | 164.26297300744397 |
| 161.94000244140625 | 164.8001689853076  |
| 156.80999755859375 | 159.60050042545993 |
| 160.24000549316406 | 163.07708667144328 |
| 165.3000030517578  | 168.20579723202684 |
| 164.77000427246094 | 167.6686012541632  |
| 163.75999450683594 | 166.64487590819823 |
| 161.83999633789062 | 164.69880483378694 |
+--------------------+--------------------+
